import SWRConfigContext from '@/context/SWRConfigContext';
import './globals.css';
import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import RecoilProvider from '@/context/RecoilProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head></head>
      <body className="flex flex-col min-h-screen items-center">
        <RecoilProvider>
          <SWRConfigContext>
            <div className="w-full max-w-md">{children}</div>
          </SWRConfigContext>
        </RecoilProvider>
      </body>
    </html>
  );
}
